### ISSUE TITLE
[Request] Add description on AD Group

### ISSUE THREAD

**Issue by wikijm** [davegreen/shadowGroupSync#7]
Hi @davegreen,

I'm wondering if it's possible to add a description to all AD groups that the script will create?
I've tried to modify line below then add a 'Description' column, with non success: https://github.com/davegreen/shadowGroupSync/blob/4fef77b894514131de1c9c6805bb098d334a7e20/shadowGroupSync.ps1#L119

Thanks in advance.

**Comment by davegreen** [comment]
Hi @wikijm,

Wow, its interesting to know people are still using/looking at this!

I've done a quick edit in the branch called [description](https://github.com/davegreen/shadowGroupSync/tree/description), but I have done **no testing** on it yet, so be warned.  At the moment it should add a hardcoded description 'ShadowGroup'.

I may get some time tomorrow to test this and potentially add in the pull through for a description column from the CSV, since that should be a straightforward change with a new parameter to Get-ShadowGroupMembers.

**Comment by wikijm** [comment]
Thanks a lot for your time!

Yes, still used if you try to apply a fined-grained pasword policy with a 2008 R2 functional domain.

I'll make a try during this day too, and propose to update README.md and related if test get positive results 😃

**Comment by wikijm** [comment]
Not working for now, even the hardcoded value 'ShadowGroup'.

**Comment by davegreen** [comment]
OK, I realised when i applied the style fixes it broke for PS v2 :(

I fixed that and in my simple test on a fresh 2008R2 domain controller, it works with hardcoding the description for new and existing groups as 'ShadowGroup'.

<img width="512" alt="shadowgroups" src="https://user-images.githubusercontent.com/759393/35015250-6ad1f3c6-fb0b-11e7-84b1-74bfc7b5e505.png">

I'm partway done with adding the description as a field for the CSV, I'll clean it up and make sure it's backward compatible tomorrow before I push to GitHub.

**Comment by wikijm** [comment]
Everything's working perfectly, nice job @davegreen 😃 

Thanks a lot and have a nice day 😉
